version: '2'

services:
    ntrs_mysql:
        container_name: ntrs_mysql
        image: mysql:5.7
        ports:
            - 5000:3306
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        restart: always
    ntrs:
        container_name: ntrs 
        image: denzdacs/react-laravel5.5-env:latest 
        ports:
            - 80:80
        volumes:
            - .:/var/www/site
        working_dir: /var/www/site
        depends_on:
            - ntrs_mysql 
        restart: always
volumes:
    db-data:

